### ISSUE TITLE
Jam edge case

### ISSUE THREAD

**Issue by bacwyls** [stevelacy/go-urbit#2]
Jam produces a bad result for some nouns. I havent found the exact cause but an example is
```[[[1 1] 2 2] 2 2]```

using dojo:
```
> (jam [[[1 1] 2 2] 2 2])
3.886.480.388.885
> (cue 3.886.480.388.885)
[[[1 1] 2 2] 2 2]
```

some debug prints using go-urbit for the same task:
```
original: [[[1 1] 2 2] 2 2]
jammed:  5054711493397
cued:  %!v(PANIC=String method: runtime error: invalid memory address or nil pointer dereference)
```

I believe it is a failure in creating a nounmap reference for a repeated noun, in this case [2 2]. but it has to do with the location of the copy, because it works correctly on ```[[2 2] 2 2]``` for instance.

BTW, I threw together a NounFromString func which is useful in creating these test nouns:
https://gist.github.com/bacwyls/8c268b0d64b5d52bb160ead7ad6e9068

To verify that it's not an issue with my NounFromString, I reproduced the same issue using native go-urbit noun creation
```go
  a := []interface{}{1, 1}
  b := []interface{}{2, 2}
  ab := noun.MakeNoun([]interface{}{a, b}) 
  n := noun.MakeNoun([]interface{}{ab, b})
  ```
  which produced the same error

**Comment by bacwyls** [comment]
It works correctly for both ```[[1 2 2] 2 2]``` and ```[[1 1 2 2] 2 2]```

but breaks at ```[[[1 1] 2 2] 2 2]```

this is the simplest case I could find.

**Comment by stevelacy** [comment]
Thanks for reporting. The issue seems to be with pairing integer 1 `[1 1]`

**Comment by bacwyls** [comment]
```[1 1]``` appears to not be significant. for instance ```[[[44 55 66] 2 2] 2 2]``` produces the same error. it seems that the issue occurs so long as there is a cell in the position of ```[1 1]``` ?

**Comment by stevelacy** [comment]
Seems to be the map[string]int that is causing the issue.

The correct cue'ed nounmap:
```
map[2:[[1 1] 2 2] 4:[1 1] 6:1 10:1 14:[2 2] 16:2 23:2]
```

The output of jam's nounmap, inverted order:
```
map[1:6 2:20 [1 1]:4 [2 2]:18 [[1 1] 2 2]:2 [[[1 1] 2 2] 2 2]:0]
```
The nounmap stores `"[1 1]": 4`, which means `"1": 10` and `"1": 6"` overwrite each other.

Cue does not overwrite as it is index : Noun.

**Comment by bacwyls** [comment]
https://github.com/stevelacy/go-urbit/commit/24d24fbad7e5a80512c74526106665b08cfd4167
This change seems to have solved the problem. Jam was making bad indices in nounMap. Maybe index was being accidentally passed as a reference somehow? Not sure about these nuances in Go.
Also, it looks like this repo isn't open to PRs. Otherwise I would move the conversation there.

**Comment by stevelacy** [comment]
@bacwyls Interesting, I assumed it was passed by value.
I'm quite sure PRs are available, did you fork/commit to the fork?

**Comment by stevelacy** [comment]
Thanks for the contribution, I'll close this issue, can revisit if more edge cases are found
